#! /usr/bin/env sh

PLAY_VERSION="2.1-SNAPSHOT"

if [ -z "${JPDA_PORT}" ]; then
  DEBUG_PARAM=""
else
  DEBUG_PARAM="-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${JPDA_PORT}"
fi

#using Resident compiler:
#java ${DEBUG_PARAM} -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M ${JAVA_OPTS} -Dfile.encoding=UTF-8 -Dplay.version="${PLAY_VERSION}" -Dsbt.ivy.home=`dirname $0`/../repository -Dsbt.boot.properties=`dirname $0`/sbt/sbt.boot.properties -Dplay.home=`dirname $0` -Dsbt.resident.limit=1 -jar `dirname $0`/sbt/sbt-launch.jar "$@"

#using regular compiler
java ${DEBUG_PARAM} -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M ${JAVA_OPTS} -Dfile.encoding=UTF-8 -Dplay.version="${PLAY_VERSION}" -Dsbt.ivy.home=`dirname $0`/../repository -Dsbt.boot.properties=`dirname $0`/sbt/sbt.boot.properties -Dplay.home=`dirname $0` -jar `dirname $0`/sbt/sbt-launch.jar "$@"
